services:
  linter:
    image: integration-linter:latest
    container_name: integration-linter
    build:
      context: .
      dockerfile: Dockerfile.lint
    volumes:
      - .:/app
      - lint_cache:/cache

  test:
    image: integration-test:latest
    container_name: integration-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - test_cache:/cache

  lint-test:
    image: integration-lint-test:latest
    container_name: integration-lint-test
    build:
      context: .
      dockerfile: Dockerfile.lint-test
    volumes:
      - .:/app
      - lint_test_cache:/cache
volumes:
  lint_cache: {}
  test_cache: {}
  lint_test_cache: {}