services:
  mosquitto:
    image: integration-mosquitto:latest
    container_name: integration-mosquitto
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    ports:
      - "1883:1883"
    networks:
      - app_network

  postgres:
    image: postgres:17.2-alpine3.21
    container_name: integration-postgres
    environment:
      POSTGRES_USER: hurtec
      POSTGRES_PASSWORD: hurtec
      POSTGRES_DB: hurtec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hurtec"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  combined_app:
    image: integration-combined_app:latest
    container_name: integration-combined_app
    build:
      context: .
      dockerfile: Dockerfile.combined
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://hurtec:hurtec@postgres/hurtec
      MOCK_MODE: "true"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
