"""initial

Revision ID: bef73a33c4c2
Revises:
Create Date: 2025-02-14 15:37:44.180791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bef73a33c4c2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("uploaded_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
    )
    op.create_index(
        op.f("ix_certificates_uploaded_at"),
        "certificates",
        ["uploaded_at"],
        unique=False,
    )
    op.create_table(
        "gps_data",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("latitude", sa.Float(precision=9), nullable=False),
        sa.Column("longitude", sa.Float(precision=9), nullable=False),
        sa.Column("altitude", sa.Float(precision=6), nullable=False),
        sa.Column("speed", sa.Float(precision=6), nullable=False),
        sa.Column("heading", sa.Float(precision=6), nullable=False),
        sa.Column("pdop", sa.Float(precision=4), nullable=False),
        sa.Column("hdop", sa.Float(precision=4), nullable=False),
        sa.Column("vdop", sa.Float(precision=4), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("location_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gps_location", "gps_data", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "idx_gps_timestamp",
        "gps_data",
        ["timestamp", "location_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gps_data_timestamp"), "gps_data", ["timestamp"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("sent_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_timestamp_topic", "messages", ["timestamp", "topic"], unique=False
    )
    op.create_index(op.f("ix_messages_sent_on"), "messages", ["sent_on"], unique=False)
    op.create_index(
        op.f("ix_messages_timestamp"), "messages", ["timestamp"], unique=False
    )
    op.create_index(op.f("ix_messages_topic"), "messages", ["topic"], unique=False)
    op.create_table(
        "service_status",
        sa.Column("service_name", sa.String(length=100), nullable=False),
        sa.Column("status_message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("service_name"),
    )
    op.create_index(
        op.f("ix_service_status_timestamp"),
        "service_status",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iot_environment", sa.String(length=50), nullable=False),
        sa.Column("tenant_name", sa.String(length=100), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=False),
        sa.Column("aws_iot_endpoint", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_index(op.f("ix_service_status_timestamp"), table_name="service_status")
    op.drop_table("service_status")
    op.drop_index(op.f("ix_messages_topic"), table_name="messages")
    op.drop_index(op.f("ix_messages_timestamp"), table_name="messages")
    op.drop_index(op.f("ix_messages_sent_on"), table_name="messages")
    op.drop_index("idx_messages_timestamp_topic", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_gps_data_timestamp"), table_name="gps_data")
    op.drop_index("idx_gps_timestamp", table_name="gps_data")
    op.drop_index("idx_gps_location", table_name="gps_data")
    op.drop_table("gps_data")
    op.drop_index(op.f("ix_certificates_uploaded_at"), table_name="certificates")
    op.drop_table("certificates")
    # ### end Alembic commands ###
