"""gps_send

Revision ID: 88e192e9c1c7
Revises: bef73a33c4c2
Create Date: 2025-02-19 06:51:45.262616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88e192e9c1c7"
down_revision: Union[str, None] = "bef73a33c4c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_gps_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("last_sent", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_gps_data_last_sent"),
        "outbound_gps_data",
        ["last_sent"],
        unique=False,
    )
    op.alter_column(
        "gps_data",
        "latitude",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=9),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "longitude",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=9),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "altitude",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=6),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "speed",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=6),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "heading",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=6),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "pdop",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=4),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "hdop",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=4),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "vdop",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gps_data",
        "vdop",
        existing_type=sa.Float(precision=4),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "hdop",
        existing_type=sa.Float(precision=4),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "pdop",
        existing_type=sa.Float(precision=4),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "heading",
        existing_type=sa.Float(precision=6),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "speed",
        existing_type=sa.Float(precision=6),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "altitude",
        existing_type=sa.Float(precision=6),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "longitude",
        existing_type=sa.Float(precision=9),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "gps_data",
        "latitude",
        existing_type=sa.Float(precision=9),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_outbound_gps_data_last_sent"), table_name="outbound_gps_data"
    )
    op.drop_table("outbound_gps_data")
    # ### end Alembic commands ###
